name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Also update checkout action

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: 18.x
          cache: yarn  # Automatic Yarn caching!

      - name: Cache node modules
        uses: actions/cache@v3  # Fixed version here
        with:
          path: |
            node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn build
          npx auto shipit